after upload codes to docker images and create a container.
you need to create docker network to connecting all docker container in local

create docker http-server image

docker build -t http-server:v1 .

create docker container

docker run -d -p 8085:8085 --name http-server-golang -e DB_USER=amonzark -e DB_PASS=nuansa12 -e DB_HOST=postgresqldb -e DB_PORT=5432 -e DB_NAME=postgres http-server:v1

//GET List student
curl --location 'http://localhost:8085/students' \
--header 'Content-Type: application/json' \
--data ''

//POST Create student
curl --location 'http://localhost:8085/students/create' \
--header 'Content-Type: application/json' \
--data '{"ID":"F004", "name":"Grogu Stein", "age":5, "grade":9}'

//GET ID Student
curl --location 'http://localhost:8085/students/get/F004' \
--header 'Content-Type: application/json' \
--data ''

//GET Age Student
curl --location --request GET 'http://localhost:8085/students/20' \
--header 'Content-Type: application/json' \
--data ''

//POST Update Student
curl --location 'http://localhost:8085/students/update/F004' \
--header 'Content-Type: application/json' \
--data '{"age":30, "ID":"F004"}'

//POST Delete Student
curl --location --request POST 'http://localhost:8085/students/delete/F004' \
--header 'Content-Type: application/json' \
--data ''